# Generated by Django 5.0.3 on 2024-04-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_quiz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
