# Generated by Django 5.0.3 on 2024-04-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizattempt_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
