# Generated by Django 5.0.3 on 2024-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizattempt_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
