# Generated by Django 5.0.3 on 2024-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizattempt_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
